<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Pi1ElviraVgaEditor</AssemblyName>
    <RootNamespace>ElviraVgaEditor</RootNamespace>
      <Product>π1 Elvira I&amp;II VGA Editor</Product>
    <Title>π1 Elvira I&amp;II VGA Editor v1.3</Title>
    <Description>π1 Elvira I&amp;II VGA Editor</Description>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>
      <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
