using System.Reflection;
using System.Text;

namespace Pi1ElviraEditor;

internal sealed record LauncherSettings(string LauncherFile, string ModderName, string DefaultVariant = "GAMEPC")
{
    internal const string DefaultLauncherFile = "ELVIRA.BAT";
    internal const string DefaultModderName = "Pivan78";
    internal static readonly LauncherSettings Default = new(DefaultLauncherFile, DefaultModderName, "GAMEPC");
}

internal sealed record LauncherSoundOption(string Switch, string DisplayName);

/// <summary>Builds and safely deploys the runtime-only DOS launcher.  It never touches game data or executables.</summary>
internal static class LauncherService
{
    internal const string SoundStateFile = "PI1SND.BAT";
    internal const string EditorMarker = "Generated by Pi1 Elvira I & II Editor";
    internal const string GogOverlayDirectoryName = "cloud_saves";
    internal const string GogOverlayBackupFileName = "ELVOVR.BAK";
    private static readonly UTF8Encoding TextEncoding = new(false);
    private const string AnsiBrightWhite = "\x1B[1;37m";
    private const string AnsiMagentaBackground = "\x1B[45m";
    private const string AnsiReset = "\x1B[0m";

    internal static IReadOnlyList<LauncherSoundOption> SoundOptions(ElviraGameProfile game) => game switch
    {
        ElviraGameProfile.Elvira1 =>
        [new("/p", "PC Internal Speaker"), new("/t", "IBM/Tandy 3 voice"), new("/a", "AdLib sound card"),
         new("/c", "CMS Gameblaster"), new("/s", "Soundblaster music card"), new("/m0", "Generic Midi"),
         new("/m1", "Roland MT-32 / LAPC-1"), new("/m2", "Casio CT460")],
        ElviraGameProfile.Elvira2 =>
        [new("/p", "PC Internal speaker"), new("/t", "IBM/Tandy 3 voice"), new("/a", "AdLib sound card"),
         new("/s", "Soundblaster music card"), new("/m", "Roland MT-32 / LAPC-1")],
        _ => throw new InvalidDataException("A detected Elvira I or Elvira II installation is required.")
    };

    internal static LauncherSettings ValidateSettings(LauncherSettings settings)
    {
        string launcher = settings.LauncherFile.Trim();
        string modder = settings.ModderName.Trim();
        if (!IsValidLauncherFileName(launcher)) throw new InvalidDataException("Launcher file must be a DOS-compatible .BAT filename in the game directory.");
        if (!IsSafeBatText(modder) || modder.Length == 0) throw new InvalidDataException("Modder name contains a control character or BAT metacharacter.");
        string defaultVariant = Path.GetFileName(settings.DefaultVariant.Trim());
        if (defaultVariant.Length != 0 && !VariantConfigurationService.IsValidDataFileName(defaultVariant))
            throw new InvalidDataException("Default variant must be a configured DOS-compatible data filename.");
        return new LauncherSettings(launcher, modder, defaultVariant);
    }

    internal static bool IsValidLauncherFileName(string? name) =>
        !string.IsNullOrWhiteSpace(name) && Path.GetFileName(name) == name && name.EndsWith(".BAT", StringComparison.OrdinalIgnoreCase) &&
        GameDataFileService.IsDos83FileName(name);

    internal static bool IsSafeBatText(string? text) => !string.IsNullOrWhiteSpace(text) &&
        text.All(c => !char.IsControl(c) && "&|<>()^%!".IndexOf(c) < 0);

    internal static string GetBackupPath(string launcherPath) => Path.ChangeExtension(launcherPath, ".BAK");

    internal static bool ActiveLauncherIsExternallyModified(string launcherPath)
    {
        string bak = GetBackupPath(launcherPath);
        return File.Exists(bak) && File.Exists(launcherPath) && !File.ReadAllText(launcherPath, TextEncoding).Contains(EditorMarker, StringComparison.Ordinal);
    }

    internal static string BuildPreview(ElviraGameProfile game, VariantCatalog catalog, LauncherSettings settings, UiLanguage language, DateTime created)
    {
        settings = ValidateSettings(settings);
        List<VariantEntry> entries = ValidateLaunchEntries(catalog);
        VariantEntry? defaultEntry = entries.FirstOrDefault(e => e.DataFile.Equals(settings.DefaultVariant, StringComparison.OrdinalIgnoreCase));
        if (defaultEntry is null) throw new InvalidDataException("The configured default variant is disabled or not configured.");
        string version = AppInfo.ProductVersion;
        var lines = new List<string>
        {
            "@echo off",
            "rem ============================================================",
            $"rem {EditorMarker} v{version}",
            $"rem Modder: {settings.ModderName}",
            $"rem Created: {created:dd-MM-yyyy HH:mm}",
            "rem " + AppInfo.RepositoryUrl,
            "rem Do not edit this file manually unless you know what you do.",
            "rem ============================================================",
            "set PI1SND=",
            $"if exist {SoundStateFile} call {SoundStateFile}",
            "rem External PI1SND.BAT call is intentionally DOS-compatible."
        };
        foreach ((LauncherSoundOption option, int i) in SoundOptions(game).Select((s, i) => (s, i + 1))) lines.Add($"if \"%PI1SND%\"==\"{option.Switch}\" goto startup_sound_{i}");
        lines.Add("goto forced_setup");
        foreach ((LauncherSoundOption option, int i) in SoundOptions(game).Select((s, i) => (s, i + 1))) lines.AddRange(new[] { $":startup_sound_{i}", $"set PI1SNDNAME={option.DisplayName}", "goto menu" });
        string title = game == ElviraGameProfile.Elvira1 ? "Elvira: Mistress of the Dark" : "Elvira II: The Jaws of Cerberus";
        lines.AddRange(new[] { ":forced_setup", "set PI1FORCED=1", "goto setup_common", ":menu", "cls", "echo " + AnsiBrightWhite + AnsiMagentaBackground, $"echo Pi1 Elvira Editor v{version}", $"echo Modder: {settings.ModderName}", $"echo Created: {created:dd-MM-yyyy HH:mm}", "echo " + AppInfo.RepositoryUrl, "echo Do not edit this file manually unless you know what you do.", "echo.", "echo ==============================================", "echo " + title.ToUpperInvariant(), "echo ==============================================" });
        AppendPackedVariantLines(lines, entries);
        lines.AddRange(new[] { "echo.", "echo " + Localized(language, "Default:", "Predvolené:", "Výchozí:") + " " + defaultEntry.DisplayName, "echo " + Localized(language, "Sound:", "Zvuk:", "Zvuk:") + " %PI1SNDNAME%", "echo ==============================================", "echo " + AnsiReset, "echo.", "echo 0. " + Localized(language, "Setup", "Nastavenie", "Nastavení") + "    " + Localized(language, "ESC. Exit to DOS", "ESC. Ukončiť do DOSu", "ESC. Ukončit do DOSu"), "echo " + Localized(language, "Press ENTER to start default:", "Stlačte ENTER pre spustenie predvolenej verzie:", "Stiskněte ENTER pro spuštění výchozí verze:") + " " + defaultEntry.DisplayName, "echo " + Localized(language, "Select:", "Vyberte:", "Vyberte:"), ":read_menu", Pi1MenuCom.FileName });
        // PI1MENU returns syntactic key codes.  Reject codes beyond this actual menu
        // before descending ERRORLEVEL checks can treat them as a lower valid key.
        lines.Add("if errorlevel 38 goto launcher_exit");
        lines.Add($"if errorlevel {entries.Count + 3} goto read_menu");
        for (int i = entries.Count; i >= 1; i--) lines.Add($"if errorlevel {i + 2} goto launch_{i}");
        lines.AddRange(new[]
        {
            "if errorlevel 2 goto setup", "if errorlevel 1 goto launch_default", "goto read_menu",
            ":launch_default", $"if not exist {defaultEntry.ExeFile} goto missing_default_exe", $"if not exist {defaultEntry.DataFile} goto missing_default_data", $"goto launch_{entries.IndexOf(defaultEntry) + 1}",
            ":missing_default_exe", "echo " + Localized(language, "Default variant executable unavailable:", "Spustiteľný súbor predvoleného variantu nie je dostupný:", "Spustitelný soubor výchozí varianty není dostupný:") + " " + defaultEntry.ExeFile, "pause", "goto menu",
            ":missing_default_data", "echo " + Localized(language, "Default variant data unavailable:", "Dátový súbor predvoleného variantu nie je dostupný:", "Datový soubor výchozí varianty není dostupný:") + " " + defaultEntry.DataFile, "pause", "goto menu"
        });
        for (int i = 0; i < entries.Count; i++)
        {
            VariantEntry e = entries[i];
            lines.AddRange(new[]
            {
                $":launch_{i + 1}",
                $"if not exist {e.ExeFile} goto missing_exe_{i + 1}",
                $"if not exist {e.DataFile} goto missing_data_{i + 1}",
                $"{ExecutableInvocation(e.ExeFile)} {e.DataFile} %PI1SND%", "goto menu",
                $":missing_exe_{i + 1}", $"echo {Localized(language, "Missing executable:", "Chýbajúci spustiteľný súbor:", "Chybějící spustitelný soubor:")} {e.ExeFile}", "pause", "goto menu",
                $":missing_data_{i + 1}", $"echo {Localized(language, "Missing data file:", "Chýbajúci dátový súbor:", "Chybějící datový soubor:")} {e.DataFile}", "pause", "goto menu"
            });
        }
        lines.AddRange(BuildSoundProcedures(game, language));
        lines.AddRange(new[] { ":launcher_exit", "set PI1SNDNAME=", "set PI1FORCED=", "goto launcher_end", ":launcher_end", "rem Physical end of launcher BAT; COMMAND.COM returns to its prompt." });
        return string.Join("\r\n", lines) + "\r\n";
    }

    internal static void Generate(ElviraGameProfile game, VariantCatalog catalog, LauncherSettings settings, UiLanguage language, bool allowExternalOverwrite)
    {
        settings = ValidateSettings(settings);
        string content = BuildPreview(game, catalog, settings, language, DateTime.Now);
        string active = Path.Combine(catalog.InstallationDirectory, settings.LauncherFile);
        string backup = GetBackupPath(active);
        string? overlayDirectory = GetExistingGogOverlayDirectory(catalog.InstallationDirectory);
        string? overlayActive = overlayDirectory is null ? null : Path.Combine(overlayDirectory, settings.LauncherFile);
        string overlayBackup = Path.Combine(catalog.InstallationDirectory, GogOverlayBackupFileName);
        if (ActiveLauncherIsExternallyModified(active) && !allowExternalOverwrite)
            throw new InvalidOperationException("The active launcher was changed outside the editor. Confirmation is required before replacement.");
        string temp = active + ".PI1TMP";
        string? overlayTemp = overlayActive is null ? null : overlayActive + ".PI1TMP";
        if (File.Exists(temp)) File.Delete(temp);
        if (overlayTemp is not null && File.Exists(overlayTemp)) File.Delete(overlayTemp);
        try
        {
            if (File.Exists(active) && !File.Exists(backup)) File.Copy(active, backup, overwrite: false);
            if (overlayActive is not null && File.Exists(overlayActive) && !File.Exists(overlayBackup)) File.Copy(overlayActive, overlayBackup, overwrite: false);
            File.WriteAllBytes(Path.Combine(catalog.InstallationDirectory, Pi1MenuCom.FileName), Pi1MenuCom.Build());
            File.WriteAllText(temp, content, TextEncoding);
            File.Move(temp, active, overwrite: true);
            if (overlayTemp is not null && overlayActive is not null)
            {
                File.WriteAllText(overlayTemp, content, TextEncoding);
                File.Move(overlayTemp, overlayActive, overwrite: true);
            }
        }
        finally
        {
            if (File.Exists(temp)) File.Delete(temp);
            if (overlayTemp is not null && File.Exists(overlayTemp)) File.Delete(overlayTemp);
        }
    }

    internal static void RestoreOriginal(string installationDirectory, LauncherSettings settings)
    {
        settings = ValidateSettings(settings);
        string active = Path.Combine(installationDirectory, settings.LauncherFile);
        string backup = GetBackupPath(active);
        if (!File.Exists(backup)) throw new InvalidDataException("No original launcher backup exists.");
        string temp = active + ".PI1RESTORE";
        if (File.Exists(temp)) File.Delete(temp);
        try
        {
            File.Copy(backup, temp); File.Move(temp, active, overwrite: true);
            string? overlayDirectory = GetExistingGogOverlayDirectory(installationDirectory);
            if (overlayDirectory is null) return;
            string overlayActive = Path.Combine(overlayDirectory, settings.LauncherFile);
            string overlayBackup = Path.Combine(installationDirectory, GogOverlayBackupFileName);
            if (File.Exists(overlayBackup))
            {
                string overlayTemp = overlayActive + ".PI1RESTORE";
                try { File.Copy(overlayBackup, overlayTemp, overwrite: true); File.Move(overlayTemp, overlayActive, overwrite: true); }
                finally { if (File.Exists(overlayTemp)) File.Delete(overlayTemp); }
            }
            else if (IsGeneratedLauncher(overlayActive))
            {
                File.Delete(overlayActive);
            }
        }
        finally { if (File.Exists(temp)) File.Delete(temp); }
    }

    private static List<VariantEntry> ValidateLaunchEntries(VariantCatalog catalog)
    {
        List<VariantEntry> entries = catalog.Entries.Where(e => e.Enabled).ToList();
        if (entries.Count > 35) throw new InvalidDataException("Launcher supports at most 35 enabled variants.");
        foreach (VariantEntry e in entries)
        {
            if (!IsSafeBatText(e.DisplayName)) throw new InvalidDataException($"Variant display name contains a BAT metacharacter: {e.DisplayName}");
            _ = VariantNaming.ValidateExeFile(e.ExeFile);
        }
        return entries;
    }

    private static string ExecutableInvocation(string exeFile) =>
        Path.GetFileNameWithoutExtension(VariantNaming.ValidateExeFile(exeFile));

    private static string? GetExistingGogOverlayDirectory(string installationDirectory)
    {
        string overlay = Path.Combine(installationDirectory, GogOverlayDirectoryName);
        return Directory.Exists(overlay) ? overlay : null;
    }

    private static bool IsGeneratedLauncher(string path) =>
        File.Exists(path) && File.ReadAllText(path, TextEncoding).Contains(EditorMarker, StringComparison.Ordinal);

    private static IEnumerable<string> BuildSoundProcedures(ElviraGameProfile game, UiLanguage language)
    {
        string title = game == ElviraGameProfile.Elvira1 ? "Elvira: Mistress of the Dark" : "Elvira II: The Jaws of Cerberus";
        var lines = new List<string> { ":setup", "set PI1FORCED=0", "goto setup_common", ":setup_common", "cls", "if \"%PI1FORCED%\"==\"1\" echo " + Localized(language, "No sound device has been configured.", "Zvukové zariadenie nie je nastavené.", "Zvukové zařízení není nastaveno."), Pi1MenuCom.FileName + " /logo", "echo " + title, "echo.", "echo " + Localized(language, "Sound Setup", "Nastavenie zvuku", "Nastavení zvuku"), "echo." };
        foreach ((LauncherSoundOption option, int i) in SoundOptions(game).Select((s, i) => (s, i + 1))) lines.Add($"echo {i}. {option.DisplayName}");
        lines.Add("if \"%PI1FORCED%\"==\"1\" goto setup_forced_gap");
        lines.Add("echo 0. " + Localized(language, "Back", "Späť", "Zpět"));
        lines.Add("goto setup_no_back");
        lines.Add(":setup_forced_gap"); lines.Add("echo.");
        lines.Add(":setup_no_back");
        lines.Add("echo."); lines.Add("echo " + Localized(language, "Current:", "Aktuálny:", "Aktuální:") + " %PI1SNDNAME%"); lines.Add("echo " + Localized(language, "Select:", "Vyberte:", "Vyberte:")); lines.Add("echo.");
        lines.AddRange(TributeLines());
        int soundCount = SoundOptions(game).Count;
        lines.AddRange(new[] { ":read_setup", Pi1MenuCom.FileName });
        lines.Add($"if errorlevel {soundCount + 3} goto read_setup");
        for (int i = soundCount; i >= 1; i--) lines.Add($"if errorlevel {i + 2} goto set_sound_{i}");
        lines.Add("if errorlevel 2 goto setup_back"); lines.Add("goto read_setup");
        lines.AddRange(new[] { ":setup_back", "if \"%PI1FORCED%\"==\"1\" goto read_setup", "goto menu" });
        foreach ((LauncherSoundOption option, int i) in SoundOptions(game).Select((s, i) => (s, i + 1))) lines.AddRange(new[] { $":set_sound_{i}", $">{SoundStateFile} echo SET PI1SND={option.Switch}", $"if not exist {SoundStateFile} goto sound_write_error", $"set PI1SND={option.Switch}", $"set PI1SNDNAME={option.DisplayName}", "goto menu" });
        lines.AddRange(new[] { ":sound_write_error", "echo Unable to save sound configuration.", "pause", "goto forced_setup" });
        return lines;
    }

    private static IEnumerable<string> TributeLines() => new[]
    {
        "echo Remember these crews? :)",
        "echo.",
        "echo Phrozen Crew, UCF, CORE, PARADOX, Razor 1911, Fairlight, TRSi, INC,",
        "echo Hybrid, Prestige, CLASS, MYTH, Drink Or Die, DREAD, ORiON, ECLiPSE",
        "echo.",
        "echo A little tribute to the scene that made DOS history.",
        "echo No affiliation or endorsement implied."
    };

    private static void AppendPackedVariantLines(List<string> lines, IReadOnlyList<VariantEntry> entries)
    {
        const string gap = "    ";
        string current = "echo ";
        foreach ((VariantEntry entry, int i) in entries.Select((e, i) => (e, i + 1)))
        {
            string unit = $"{MenuKey(i)}. {entry.DisplayName}";
            string candidate = current == "echo " ? current + unit : current + gap + unit;
            if (candidate.Length > 80 && current != "echo ") { lines.Add(current); current = "echo " + unit; }
            else current = candidate;
        }
        if (current != "echo ") lines.Add(current);
    }

    private static char MenuKey(int index) => index <= 9 ? (char)('0' + index) : (char)('A' + index - 10);
    private static string Localized(UiLanguage l, string en, string sk, string cz) => l == UiLanguage.Slovak ? sk : l == UiLanguage.Czech ? cz : en;
}
